services:
  - type: web
    name: frontend-practimatch
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://dashboard-practimatch.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
